### PR TITLE
gender neutral?

### PR DESCRIPTION
**Pull request by maelle**
(I think Mauro's comment was partially forgotten so making a PR where we can discuss :-D)

### CODE REVIEW

**Comment by maurolepore** [comment]
Thanks!

The [guidelines](https://github.com/cienciadedatos/documentacion-traduccion-r4ds/commit/eec388579e7be9ed632145bf8b78276e88823e12#diff-4e7c7fbe82fe8302d57adb66b825f64d0d12998e4ab6bf8db6a037c3ee28277eL17) I thought about are these:

> En principio, las dos opciones más habituales que se han seguido en traducciones de este tipo son: 

> * Usar el femenino para incluir un género gramatical poco representado: _para colaborar con otras científicas de datos._ 
> * Ajustar la redacción para evitar tener que asignar un género: _para colaborar con otras personas que trabajan en Ciencia de Datos._


However, I'm surprised that in the [public-facing version](https://github.com/cienciadedatos/documentacion-traduccion-r4ds/blob/master/orientaciones-traduccion.md#i-aspectos-a-tener-en-cuenta-para-la-traducci%C3%B3n-del-texto) the dotpoints are gone.

It would be so great to engage [Riva](https://twitter.com/rivaquiroga) in this process to build on her experience.

**Review by maurolepore — COMMENTED** [review]
Given the intent of this PR is to open the discussion, for now I limit my review to "Comment".

**Comment by maelle** [comment]
Maybe the easiest solution for now is to use the feminine then? :thinking:

**Comment by maurolepore** [comment]
I like the idea of using the feminine. When I read text in the feminine form -- where I unconsciously expected the masculine form -- I am forced to confront my own biases. It is a little distracting and hurts, but I think it's useful.

**Comment by maurolepore** [comment]
I'm so curious to know why that guideline went away from the guidelines of Riva et al.

**Review by maurolepore — APPROVED** [review]

**Pull request merged**
