### PR TITLE
Clarify what to write in NEWS.md

### PR DESCRIPTION
**Pull request by maurolepore**
This PR aims to clarify what authors should write in NEWS.md.

I note our request deviates from https://style.tidyverse.org/news.html
-- which focuses only on changes that face users -- and from
the practice of documenting changes after the first public
release. 

However, our approach is nice in that it leaves a record of the
peer-review that is more discoverable and readable than the
scattered comments in the review issue, where authors tell
reviewers how they addressed their requests.

I plan to follow up with a PR to the template in Spanish, but
to avoid working on a moving target, I suggest we discuss this
PR first.
﻿

### CODE REVIEW

**Review by annakrystalli — APPROVED** [review]
Nice and clear! 👍

**Review by maelle — APPROVED** [review]
Thank you!

**Comment by maurolepore** [comment]
@maelle,

Do we expect the bot to start using the latest version of this template automatically?

It seems the changes introduced in this PR are NOT reflected in a [issue-comment](https://github.com/ropensci/software-review/issues/463#issuecomment-955576106):
> Please check you updated the package version post-review version updated and that you documented all changes in NEWS.md

**Comment by maelle** [comment]
@xuanxu is there some caching in the template fetching? We edited the template 28 days ago but a comment from 2 days ago seems to have used the old version.

**Comment by xuanxu** [comment]
[That comment](https://github.com/ropensci/software-review/issues/463#issuecomment-955576106) was not made by the review bot, maybe the editor copied from somewhere else?

**Comment by maelle** [comment]
oooh right, good call, thank you and sorry!

**Pull request merged**
